services:
  db:
    image: mysql:8.0.40-bookworm
    restart: on-failure
    environment:
      MYSQL_DATABASE: tasks
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db: